### ISSUE TITLE
Add settings page

### ISSUE THREAD

**Issue by alessandrojean** [alessandrojean/tankobon#13]
### Describe your suggested feature

A simple settings page in the client, categorized.

Display settings:
- Language
- Theme
- ~View mode (grid or table)~
- ~Grid mode (comfortable or compact)~
- Hide synopsis of unread books
- Hide covers of unread books
- Hide covers of NSFW books
- Preferred length unit
- Preferred mass unit

Privacy settings:
- Delete the account

More settings can be added as they're needed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I filled out all of the requested information in this form.

**Comment by ghostbear** [comment]
Books creation settings: 
- Default currency
- Default store
