### ISSUE TITLE
Create a documentation site

### ISSUE THREAD

**Issue by alessandrojean** [alessandrojean/tankobon#26]
### Describe your suggested feature

Can use [VitePress](https://vitepress.dev/).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I filled out all of the requested information in this form.

**Comment by ghostbear** [comment]
[AsciidoctorJ](https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-3.x/user-guide/) could be an alternative to VitePress if one wants to use Gradle as the build tool. The biggest difference between the two is that Asciidoctor doesn't use Markdown but AsciiDoc ([markup comparison](https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/))

**Comment by alessandrojean** [comment]
Closed in 7fff544
