### ISSUE TITLE
Change units for book dimension and weight 

### ISSUE THREAD

**Issue by ghostbear** [alessandrojean/tankobon#35]
### Describe your suggested feature

It would be nice if the dimension unit was `mm (millimeter)` and the weight unit was `g (grams)` 

### Other details

Most of the manga books are below 1 kg so always needing to add `0.` is a bit of a chore. While millimeter is more of a preference thing as the bookstore I use provides dimensions in millimeters 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I filled out all of the requested information in this form.

**Comment by alessandrojean** [comment]
I think a best approach would be allowing the user to change the default unit it prefers through settings, while still allowing some particular books to use other units if the user wants (as for example if it's more convenient to just copy the information as you mentioned), and converting to the unit chosen while showing if it's saved with a different one in the database.

The database would then just store `width` and `height` and a new `dimensions_unit` integer representing an enum of possible units, in the case of the dimensions for example.

I will implement this when I am doing the settings page as well.

**Comment by alessandrojean** [comment]
Closed in 119b05f.
