### ISSUE TITLE
Unable to select Collection in import dialog

### ISSUE THREAD

**Issue by ghostbear** [alessandrojean/tankobon#47]
### Steps to reproduce

1. Search for a book on the import page
2. Select a book to import
3. Unable to select a collection to import to

### Expected behavior

Able to select a collection to import to

### Actual behavior

![image](https://github.com/alessandrojean/tankobon/assets/6576096/773fe3ba-a8c0-486b-b386-275cd0350e3d)
![image](https://github.com/alessandrojean/tankobon/assets/6576096/6424c3e1-051e-4c5b-a026-c08946897fda)

### Tankobon version

a281a1b

### Operating system

Docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I filled out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Uh, that's weird. Can you show what's the response for the API requests?

**Comment by ghostbear** [comment]
What is weird is that it isn't hitting the collection endpoint

![image](https://github.com/alessandrojean/tankobon/assets/6576096/bea630ed-5590-46a7-b0a3-92364afe5f7c)
![image](https://github.com/alessandrojean/tankobon/assets/6576096/c1c4bed9-0109-4996-acea-d2e7acabce7b)
![image](https://github.com/alessandrojean/tankobon/assets/6576096/175d6dde-4fee-4954-b732-060cc6e829df)

**Comment by alessandrojean** [comment]
I guess it's because of some modifications I did on the selector component when I was making it support generic types. Will fix these days 👍🏻
